# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push to the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  publish:
    # The type of runner that the job will run on
    runs-on: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1

    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
  
    - name: Build
      run: msbuild Sitecore.Sharedsource.NewsMover.sln /p:Configuration=Release
      
    - name: Nuget Pack
      run: nuget pack Sitecore.Sharedsource.NewsMover.csproj
    
    - name: Rename Package
      run: |
        $nupkg = (dir *.nupkg) | select -First 1
        Rename-Item $nupkg $nupkg.Name.Replace("Sitecore.", "SitecorePM.")
    
    - name: Nuget Push
      run: nuget push *.nupkg -ApiKey "${{secrets.NUGET_API_KEY}}"
      
    # Runs a single command using the runners shell
    #- name: Run a one-line script
    #  run: echo Hello, world!

    # Runs a set of commands using the runners shell
    #- name: Run a multi-line script
    #  run: |
    #    echo Add other actions to build,
    #    echo test, and deploy your project.
